export const DEFAULT_WATCHLIST = ["NVDA", "TSLA", "AMD", "GOOGL", "TSM"];

export const STORAGE_KEYS = {
  watchlist: "us-stock-weekly-analyzer.watchlist",
  language: "us-stock-weekly-analyzer.language",
  theme: "us-stock-weekly-analyzer.theme"
};

export const copy = {
  zh: {
    appTitle: "美股週報分析工作台",
    subtitle: "依照你的美股週報規則，自動抓取公開行情、整理標的清單、輸出可重複使用的 Markdown 報告。",
    refresh: "更新行情",
    refreshing: "更新中",
    updateWarningPrefix: "資料提醒",
    watchlist: "我的清單",
    searchPlaceholder: "搜尋公司名，或輸入代號直接加入",
    searching: "搜尋中",
    search: "搜尋",
    addSymbol: "直接加入代號",
    waitQuote: "等待行情",
    addFirst: "先加入一個美股標的",
    addFirstHint: "搜尋代號或從右側建議清單加入，app 會在開啟時自動更新行情。",
    ideas: "建議標的",
    ideaBasis: "建議標準",
    ideaBasisText:
      "建議標的會從公開市場候選池即時抓取，再依照你的週報規則評分：長線成長、護城河、自由現金流、毛利率、估值合理性、催化劑強度與風險報酬。建議清單不是買進指令，而是優先研究名單。",
    dynamicIdeas: "動態篩選",
    loadingIdeas: "篩選建議中",
    ideasUpdated: "建議更新",
    noIdeas: "目前沒有符合條件的新建議標的。",
    score: "分數",
    loadingReport: "正在更新這個標的",
    loadingReportHint: "已加入清單，正在抓取行情、估值、財報與新聞資料。",
    darkMode: "夜間",
    lightMode: "日間",
    tracked: "追蹤標的",
    loaded: "已載入分析",
    positive: "偏正面評級",
    avgMove: "平均日漲跌",
    finalRating: "最終評級",
    valuation: "估值判斷",
    technical: "技術面",
    exportMd: "匯出 .md",
    conclusion: "一句話結論",
    dataQuality: "資料品質檢查",
    fieldsReady: "已取得",
    coreFields: "個核心欄位。",
    missing: "缺少",
    completeFields: "核心欄位完整。",
    themes: "題材與當前催化劑",
    majorNews: "重大新聞",
    noNews: "目前沒有抓到重大新聞。",
    openNews: "閱讀完整內容",
    valuationMethod: "估值方法",
    valuationModels: "估值模型切換",
    catalystTimeline: "催化劑時間表",
    revenueTrend: "營收與獲利趨勢",
    financialDetail: "財報細項與成本判斷",
    financialDetailTip:
      "這裡拆解 TTM 與年度損益表，重點看營收成本、營業費用、研發費用、資本支出與成本變動原因，用來判斷成本上升是投資擴張還是獲利壓力。",
    costJudgement: "成本增加判斷",
    financials: "財報與財務狀況",
    financialsTip:
      "這裡看公司目前財務體質，包括營收、EPS、自由現金流、毛利率、營業利益率、淨利率、現金、負債、ROE、ROIC 與持股結構。",
    longTermPlan: "長期計劃與發展路線",
    longTermPlanHint: "依據公司題材、催化劑、護城河、客戶/供應鏈與財報預估整理，作為未來 thesis 追蹤清單。",
    mindMap: "投資心智圖",
    mindMapHint: "把長線 thesis 拆成護城河、成長催化、財務品質、估值紀律與主要風險，方便快速複盤。",
    strategicPillars: "發展主軸",
    executionSignals: "追蹤訊號",
    validationMetrics: "驗證指標",
    peerCompare: "清單標的比較",
    watchlistCompare: "清單標的比較",
    industryPeers: "同業標的 (市場建議)",
    dataSource: "數據來源",
    peerSource: "推薦來源",
    targetPrice: "目標價與市場預期",
    priceZones: "價格區間",
    moat: "護城河分析",
    ownership: "董監事持股 / 異動",
    risks: "主要風險",
    tableSymbol: "標的",
    tableMarketCap: "市值",
    tablePE: "PE",
    tableForwardPE: "Forward PE",
    tablePS: "PS",
    tableFCFYield: "FCF Yield",
    tableRevGrowth: "營收成長",
    tableGrossMargin: "毛利率",
    tableNetMargin: "淨利率",
    tablePriceTarget: "目標價差距",
    tableRating: "評級",
    tabOverview: "總覽",
    tabValuation: "估值",
    tabFinancials: "財報",
    tabIndustry: "產業與風險",
    swot: "SWOT 客觀分析",
    swotS: "優勢 (Strengths)",
    swotW: "劣勢 (Weaknesses)",
    swotO: "機會 (Opportunities)",
    swotT: "威脅 (Threats)",
    industry: "產業分類",
    sector: "板塊",
    footer: "資料僅供研究流程使用，不構成個人化投資建議。"
  },
  en: {
    appTitle: "US Stock Weekly Analysis Workbench",
    subtitle:
      "A reusable weekly research workflow that refreshes public market data, organizes your watchlist, and exports Markdown reports.",
    refresh: "Refresh Data",
    refreshing: "Refreshing",
    updateWarningPrefix: "Data Notice",
    watchlist: "My Watchlist",
    searchPlaceholder: "Search company name, or enter a ticker",
    searching: "Searching",
    search: "Search",
    addSymbol: "Add Ticker",
    waitQuote: "Waiting for quote",
    addFirst: "Add a US stock first",
    addFirstHint: "Search for a ticker or add one from the idea list. Data refreshes automatically when the app opens.",
    ideas: "Suggested Ideas",
    ideaBasis: "Selection Criteria",
    ideaBasisText:
      "Ideas are fetched from a live public-market candidate pool and scored by your weekly-report rules: long-term growth, moat, free cash flow, gross margin, valuation discipline, catalyst strength, and risk/reward. These are research ideas, not buy signals.",
    dynamicIdeas: "Dynamic Screen",
    loadingIdeas: "Screening Ideas",
    ideasUpdated: "Ideas Updated",
    noIdeas: "No new suggested ideas currently match the screen.",
    score: "Score",
    loadingReport: "Updating This Stock",
    loadingReportHint: "Added to your watchlist. Fetching quote, valuation, financials, and news.",
    darkMode: "Dark",
    lightMode: "Light",
    tracked: "Tracked Stocks",
    loaded: "Loaded Reports",
    positive: "Positive Ratings",
    avgMove: "Avg Daily Move",
    finalRating: "Final Rating",
    valuation: "Valuation",
    technical: "Technical",
    exportMd: "Export .md",
    conclusion: "One-Line Conclusion",
    dataQuality: "Data Quality Check",
    fieldsReady: "Collected",
    coreFields: "core fields.",
    missing: "Missing",
    completeFields: "Core fields are complete.",
    themes: "Themes and Current Catalysts",
    majorNews: "Major News",
    noNews: "No major news was fetched.",
    openNews: "Read full article",
    valuationMethod: "Valuation Method",
    valuationModels: "Valuation Model Switcher",
    catalystTimeline: "Catalyst Timeline",
    revenueTrend: "Revenue and Profit Trend",
    financialDetail: "Detailed Financials and Cost Check",
    financialDetailTip:
      "Breaks down TTM and annual income-statement details, focusing on cost of revenue, operating expenses, R&D, capex, and whether cost increases look like investment or margin pressure.",
    costJudgement: "Cost Increase Assessment",
    financials: "Financial Position",
    financialsTip:
      "Checks the company’s financial health: revenue, EPS, free cash flow, gross margin, operating margin, net margin, cash, debt, ROE, ROIC, and ownership structure.",
    longTermPlan: "Long-Term Plan and Roadmap",
    longTermPlanHint:
      "Built from the company theme, catalysts, moat, customers/supply chain, and forward financial estimates. Use it as a thesis-tracking checklist.",
    mindMap: "Investment Mind Map",
    mindMapHint:
      "Connects long-term thesis, moat, growth catalysts, financial quality, valuation discipline, and key risks for faster review.",
    strategicPillars: "Strategic Pillars",
    executionSignals: "Execution Signals",
    validationMetrics: "Validation Metrics",
    peerCompare: "Watchlist Comparison",
    watchlistCompare: "Watchlist Comparison",
    industryPeers: "Industry Peers (Market Suggested)",
    dataSource: "Data Source",
    peerSource: "Recommendation Source",
    targetPrice: "Target Price and Market Expectations",
    priceZones: "Price Zones",
    moat: "Moat Analysis",
    ownership: "Insider / Institutional Ownership",
    risks: "Key Risks",
    tableSymbol: "Symbol",
    tableMarketCap: "Market Cap",
    tablePE: "PE",
    tableForwardPE: "Forward PE",
    tablePS: "PS",
    tableFCFYield: "FCF Yield",
    tableRevGrowth: "Rev Growth",
    tableGrossMargin: "Gross Margin",
    tableNetMargin: "Net Margin",
    tablePriceTarget: "Target Gap",
    tableRating: "Rating",
    tabOverview: "Overview",
    tabValuation: "Valuation",
    tabFinancials: "Financials",
    tabIndustry: "Industry & Risk",
    swot: "SWOT Objective Analysis",
    swotS: "Strengths",
    swotW: "Weaknesses",
    swotO: "Opportunities",
    swotT: "Threats",
    industry: "Industry",
    sector: "Sector",
    footer: "Data is for research workflow only and is not personalized investment advice."
  }
};

export const valueCopy = {
  en: {
    強力買入: "Strong Buy",
    分批買入: "Staged Buy",
    續抱: "Hold",
    觀望: "Watch",
    減碼: "Trim",
    避開: "Avoid",
    明顯低估: "Clearly Undervalued",
    合理偏低: "Reasonably Low",
    合理: "Fair",
    合理偏高: "Reasonably High",
    明顯高估: "Clearly Overvalued",
    資料不足: "Insufficient Data",
    偏多: "Bullish",
    中性: "Neutral",
    偏空: "Bearish",
    完整: "Complete",
    "可用但需補強": "Usable, Needs More Data"
  }
};
